package com.vpk.sprachninja.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GeminiRequest(
    val contents: List<Content>
)

@Serializable
data class Content(
    val parts: List<Part>
)

@Serializable
data class Part(
    val text: String
)

/**
 * The top-level response object from the Gemini API.
 */
@Serializable
data class GeminiResponse(
    val candidates: List<Candidate>? = null,
    val promptFeedback: PromptFeedback? = null
)

/**
 * A potential response generated by the model.
 */
@Serializable
data class Candidate(
    val content: Content? = null,
    @SerialName("finishReason")
    val finishReason: String? = null,
    val index: Int? = null,
    val safetyRatings: List<SafetyRating>? = null
)

/**
 * A feedback object detailing any issues with the prompt.
 */
@Serializable
data class PromptFeedback(
    val safetyRatings: List<SafetyRating>? = null
)

/**
 * A rating indicating the safety level of a particular category.
 */
@Serializable
data class SafetyRating(
    val category: String? = null,
    val probability: String? = null
)