package com.vpk.sprachninja.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single question that has been recently shown to the user.
 * This is stored to prevent the Gemini API from generating the same question repeatedly.
 *
 * @property id The unique identifier for the entry, auto-generated by Room.
 * @property questionText The exact text of the question that was asked.
 * @property userLevel The proficiency level at which this question was asked (e.g., "A1.1").
 */
@Entity(tableName = "recentquestion")
data class RecentQuestion(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val questionText: String,
    val userLevel: String
)