package com.vpk.sprachninja.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user profile stored in the local database.
 *
 * @property id The unique identifier for the user, auto-generated by Room.
 * @property username The name provided by the user during onboarding.
 * @property germanLevel The German proficiency level selected by the user (e.g., "A1.1").
 */
@Entity(tableName = "user")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val username: String,
    val germanLevel: String
)